### ISSUE TITLE
Tracking incoming logs issue with date selection

### ISSUE THREAD

**Issue by flaviozluca** [polarismail/Admin-Panel#2]
See how strange. Today is the 24th. I cant choose, initially from 23rd to the 23rd (track yesterday's received emails)... System wont accept. Today is the 24th.

I have to trick the system, choose from 22, then to 23, then from 23 and to 23 ;)

**Comment by polarismail** [comment]
This has been solved in today's release - please verify

**Comment by flaviozluca** [comment]
Yep, solved. Thank you.
