### ISSUE TITLE
date range selection in outgoing logs 

### ISSUE THREAD

**Issue by flaviozluca** [polarismail/Admin-Panel#3]
I have selected FROM a certain date in November until a certain date in December.

I then change the FROM DATE to some other date. The TO date changes to the same date I set in FROM.

**Comment by polarismail** [comment]
issue fixed, please verify

**Comment by flaviozluca** [comment]
Yep, it's Ok. Thanks for the fast fix.

**Comment by polarismail** [comment]
closing fixed issue
